uploads = []
generated = []

[[outputs]]
id = "6xhpRCIowR28V-c5tcyqZ"
uri = "file://PMT_E2E.ledger.json"
type = "unspecified"
title = "PMT_E2E — Canonical Ledger (spec v2.12)"

[[outputs]]
id = "ZIOlOjQ3EloBAOPsKzQB9"
uri = "file://Row1_Understanding_E2E_Run_1.json"
type = "unspecified"
title = "Row1_Understanding_E2E_Run_1 — Canonical Ledger (spec v2.12)"

[[outputs]]
id = "4hlX126U04uPJWSr5LQFH"
uri = "file://verification_outputs/NQPS_E2E_Run_1.json"
type = "unspecified"
title = "NQPS_E2E_Run_1 — Canonical Ledger (spec v2.12)"

[[outputs]]
id = "Y1cQXUfVHo_2M2IG8X2jU"
uri = "file://verification_outputs/PMT_E2E_Post_Row2.json"
type = "unspecified"
title = "PMT_E2E_Post_Row2 — Canonical Ledger (spec v2.12)"

[[outputs]]
id = "hHI6BjPNiOas8tFdLzhCn"
uri = "file://verification_outputs/Row1_Understanding_E2E_Post_Row2.json"
type = "unspecified"
title = "Row1_Understanding_E2E_Post_Row2 — Canonical Ledger (spec v2.12)"
