uploads = []
generated = []

[[outputs]]
id = "6xhpRCIowR28V-c5tcyqZ"
uri = "file://PMT_E2E.ledger.json"
type = "unspecified"
title = "PMT_E2E — Canonical Ledger (spec v2.12)"

[[outputs]]
id = "ZIOlOjQ3EloBAOPsKzQB9"
uri = "file://Row1_Understanding_E2E_Run_1.json"
type = "unspecified"
title = "Row1_Understanding_E2E_Run_1 — Canonical Ledger (spec v2.12)"

[[outputs]]
id = "4hlX126U04uPJWSr5LQFH"
uri = "file://verification_outputs/NQPS_E2E_Run_1.json"
type = "unspecified"
title = "NQPS_E2E_Run_1 — Canonical Ledger (spec v2.12)"

[[outputs]]
id = "Y1cQXUfVHo_2M2IG8X2jU"
uri = "file://verification_outputs/PMT_E2E_Post_Row2.json"
type = "unspecified"
title = "PMT_E2E_Post_Row2 — Canonical Ledger (spec v2.12)"

[[outputs]]
id = "hHI6BjPNiOas8tFdLzhCn"
uri = "file://verification_outputs/Row1_Understanding_E2E_Post_Row2.json"
type = "unspecified"
title = "Row1_Understanding_E2E_Post_Row2 — Canonical Ledger (spec v2.12)"

[[outputs]]
id = "gmwUmbfimKnW7L6x8cRvg"
uri = "file://verification_outputs/NQPS_E2E_Post_Row2.json"
type = "unspecified"
title = "NQPS_E2E_Post_Row2 — Canonical Ledger (spec v2.12)"

[[outputs]]
id = "la8eMqkfbLSnjA7ypLjFC"
uri = "file://verification_outputs/PMT_E2E_Post_Row3.json"
type = "unspecified"
title = "PMT_E2E_Post_Row3 — Canonical Ledger (spec v2.12)"

[[outputs]]
id = "_7xy-BIHfDYAZI_xR8fek"
uri = "file://verification_outputs/NQPS_E2E_Post_Row3.json"
type = "unspecified"
title = "NQPS_E2E_Post_Row3 — Canonical Ledger (spec v2.12)"

[[outputs]]
id = "pl87bRdRM0d8yUPDF0WJt"
uri = "file://verification_outputs/Row1_Understanding_E2E_Post_Row3.json"
type = "unspecified"
title = "Row1_Understanding_E2E_Post_Row3 — Canonical Ledger (spec v2.12)"

[[outputs]]
id = "IWBhYadkRx3HnFvWpdULM"
uri = "file://verification_outputs/PMT_E2E_Post_Row4.json"
type = "unspecified"
title = "PMT_E2E_Post_Row4 — Canonical Ledger (spec v2.12)"

[[outputs]]
id = "EX0dUA_Wh14-9N4VAbGAm"
uri = "file://verification_outputs/NQPS_E2E_Post_Row4.json"
type = "unspecified"
title = "NQPS_E2E_Post_Row4 — Canonical Ledger (spec v2.12)"

[[outputs]]
id = "IM8H35ukDCAfTfHbxY1NW"
uri = "file://verification_outputs/Row1_Understanding_E2E_Post_Row4.json"
type = "unspecified"
title = "Row1_Understanding_E2E_Post_Row4 — Canonical Ledger (spec v2.12)"

[[outputs]]
id = "1ecBFlpT6aifnJ3EhroGV"
uri = "file://verification_outputs/PMT_E2E_Post_Row5.json"
type = "unspecified"
title = "PMT_E2E_Post_Row5 — Canonical Ledger (spec v2.12)"

[[outputs]]
id = "XwCImg442isAm-8TVbg_9"
uri = "file://verification_outputs/NQPS_E2E_Post_Row5.json"
type = "unspecified"
title = "NQPS_E2E_Post_Row5 — Canonical Ledger (spec v2.12)"

[[outputs]]
id = "sWud4074JrMlEZMtJZkTd"
uri = "file://verification_outputs/Row1_Understanding_E2E_Post_Row5.json"
type = "unspecified"
title = "Row1_Understanding_E2E_Post_Row5 — Canonical Ledger (spec v2.12)"

[[outputs]]
id = "F8EXJRXLiUKLgaADrqyS9"
uri = "file://verification_outputs/PMT_E2E.ledger.json"
type = "unspecified"
title = "PMT_E2E Canonical Ledger — Phase 3b"

[[outputs]]
id = "7nHc4uJKrerQlGSt3hQOZ"
uri = "file://verification_outputs/PMT_E2E_phase3b_row_1.json"
type = "unspecified"
title = "PMT_E2E Phase 3b Row 1 Ledger (Signals + ZachmanCells + CCIs)"

[[outputs]]
id = "DqDVlir3ZFFNTsy9s1-Hz"
uri = "file://verification_outputs/NQPS_Ph03_3b_CCIConstruction_R5_Run1.json"
type = "unspecified"
title = "NQPS_E2E Canonical Ledger — Phase 3b (Row 5)"

[[outputs]]
id = "MwhU4LiAq9SXciiZcEjxk"
uri = "file://verification_outputs/NQPS_Ph03_3b_CCIConstruction_R5_Run3.json"
type = "unspecified"
title = "NQPS_E2E Clean Ledger — Phase 3b (Row 5, Run3)"
