uploads = []
generated = []

[[outputs]]
id = "6xhpRCIowR28V-c5tcyqZ"
uri = "file://PMT_E2E.ledger.json"
type = "unspecified"
title = "PMT_E2E — Canonical Ledger (spec v2.12)"

[[outputs]]
id = "ZIOlOjQ3EloBAOPsKzQB9"
uri = "file://Row1_Understanding_E2E_Run_1.json"
type = "unspecified"
title = "Row1_Understanding_E2E_Run_1 — Canonical Ledger (spec v2.12)"
