"""
Named entity vocabulary for Stage 3a-pre heuristic detection (v0.14).

Used by the enumeration pre-processor in step3_cci_derivation.py to evaluate:
  Criterion 2 — items are proper nouns or named entities
  Criterion 3 — category homogeneity (all items in same semantic class)
  Criterion 4 — column affinity (Where, Who, or What; not Why/When/How)

Structure
---------
NAMED_ENTITY_CATEGORIES
    dict: category_name → {
        "column_affinity": str  — Zachman column this category belongs to,
        "terms": set[str]       — lowercase canonical forms of known named entities
    }

NAMED_ENTITY_LOOKUP
    Flat dict: lowercase term → category_name (derived from NAMED_ENTITY_CATEGORIES).
    O(1) lookup used at runtime — do not import NAMED_ENTITY_CATEGORIES directly
    in hot paths; import NAMED_ENTITY_LOOKUP instead.

Adding entries
--------------
Add terms to the appropriate category's "terms" set in NAMED_ENTITY_CATEGORIES.
NAMED_ENTITY_LOOKUP is derived automatically at module load time — do not edit it.
Terms should be lowercase canonical forms (e.g. "ios", "windows server 2022").
"""

from __future__ import annotations

NAMED_ENTITY_CATEGORIES: dict[str, dict] = {
    "platform_os": {
        "column_affinity": "Where",
        "terms": {
            "ios",
            "android",
            "windows",
            "windows server",
            "windows 10",
            "windows 11",
            "windows 7",
            "windows 8",
            "macos",
            "mac os",
            "mac os x",
            "os x",
            "linux",
            "ubuntu",
            "debian",
            "centos",
            "rhel",
            "red hat",
            "red hat enterprise linux",
            "fedora",
            "arch linux",
            "alpine",
            "alpine linux",
            "chromeos",
            "chrome os",
            "ipados",
            "watchos",
            "tvos",
            "android tv",
            "tizen",
            "harmonyos",
            "sailfishos",
        },
    },
    "cloud_infrastructure": {
        "column_affinity": "Where",
        "terms": {
            "aws",
            "amazon web services",
            "azure",
            "microsoft azure",
            "gcp",
            "google cloud",
            "google cloud platform",
            "heroku",
            "kubernetes",
            "k8s",
            "openshift",
            "red hat openshift",
            "alibaba cloud",
            "oracle cloud",
            "oracle cloud infrastructure",
            "oci",
            "ibm cloud",
            "digitalocean",
            "digital ocean",
            "linode",
            "akamai cloud",
            "vultr",
            "cloudflare",
            "cloudflare workers",
            "vercel",
            "netlify",
            "render",
            "railway",
            "fly.io",
        },
    },
    "network_component": {
        "column_affinity": "Where",
        "terms": {
            "nginx",
            "apache",
            "iis",
            "traefik",
            "haproxy",
            "caddy",
            "envoy",
            "istio",
            "linkerd",
            "kong",
            "cdn",
            "cloudfront",
            "akamai",
            "fastly",
            "redis",
            "memcached",
            "rabbitmq",
            "kafka",
            "activemq",
            "postgresql",
            "mysql",
            "mariadb",
            "mongodb",
            "cassandra",
            "elasticsearch",
            "opensearch",
            "neo4j",
            "dynamodb",
            "cosmos db",
            "firestore",
            "firebase",
            "sqlite",
            "s3",
            "blob storage",
            "gcs",
        },
    },
    "geographic_location": {
        "column_affinity": "Where",
        "terms": {
            "london",
            "new york",
            "singapore",
            "dublin",
            "frankfurt",
            "tokyo",
            "sydney",
            "chicago",
            "seattle",
            "paris",
            "amsterdam",
            "hong kong",
            "toronto",
            "berlin",
            "mumbai",
            "sao paulo",
            "virginia",
            "ohio",
            "oregon",
            "california",
            "europe",
            "north america",
            "asia pacific",
            "apac",
            "emea",
            "us east",
            "us west",
            "eu west",
            "eu central",
            "ap southeast",
            "ap northeast",
        },
    },
    "actor_role": {
        "column_affinity": "Who",
        "terms": {
            "child",
            "parent",
            "guardian",
            "admin",
            "administrator",
            "user",
            "end user",
            "manager",
            "operator",
            "analyst",
            "practitioner",
            "stakeholder",
            "developer",
            "engineer",
            "support",
            "support agent",
            "auditor",
            "guest",
            "member",
            "owner",
            "moderator",
            "supervisor",
            "reviewer",
            "approver",
            "requester",
            "contributor",
            "viewer",
            "editor",
            "author",
            "reader",
            "subscriber",
            "customer",
            "client",
            "supplier",
            "vendor",
            "partner",
            "regulator",
            "compliance officer",
            "data controller",
            "data processor",
        },
    },
    "data_entity": {
        "column_affinity": "What",
        "terms": {
            "transaction",
            "account",
            "record",
            "entity",
            "document",
            "category",
            "profile",
            "report",
            "ledger",
            "log",
            "event",
            "order",
            "invoice",
            "payment",
            "subscription",
            "product",
            "item",
            "asset",
            "contract",
            "claim",
            "ticket",
            "request",
            "response",
            "message",
            "notification",
            "session",
            "token",
            "credential",
            "permission",
            "policy",
            "rule",
            "configuration",
            "setting",
            "preference",
            "workflow",
            "pipeline",
            "task",
            "job",
            "schedule",
        },
    },
}

NAMED_ENTITY_LOOKUP: dict[str, str] = {
    term: category
    for category, info in NAMED_ENTITY_CATEGORIES.items()
    for term in info["terms"]
}
